##############################################################################
# BueaDelights Official Website - Netlify Configuration
# Optimized for premium Cameroonian food delivery platform
# Built with React + Vite + TypeScript + PWA capabilities
##############################################################################

[build]
  # Build command for Vite React app
  command = "npm run build"
  
  # Directory with build output (Vite default)
  publish = "dist"
  
  # Environment variables for build
  [build.environment]
    NODE_VERSION = "18"
    NPM_VERSION = "9"
    VITE_WHATSAPP_NUMBER = "237699808260"
    VITE_BUSINESS_NAME = "BueaDelights"
    VITE_SITE_URL = "https://bueadelights.com"

##############################################################################
# REDIRECTS & REWRITES
##############################################################################

# SPA fallback for client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# WhatsApp direct redirect for mobile users
[[redirects]]
  from = "/whatsapp"
  to = "https://wa.me/237699808260?text=Bonjour%20BueaDelights!%20Je%20souhaite%20passer%20une%20commande."
  status = 301
  force = true

# Menu shortcut redirect
[[redirects]]
  from = "/order"
  to = "/menu"
  status = 301

# Contact shortcut to WhatsApp
[[redirects]]
  from = "/commande"
  to = "https://wa.me/237699808260"
  status = 301
  force = true

# Legacy redirects if migrating from old site
[[redirects]]
  from = "/old-menu"
  to = "/menu"
  status = 301

[[redirects]]
  from = "/contact-us"
  to = "/contact"
  status = 301

##############################################################################
# HEADERS FOR SECURITY & PERFORMANCE
##############################################################################

# Global security headers
[[headers]]
  for = "/*"
  [headers.values]
    # Security Headers
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=(self), payment=()"
    
    # HSTS for HTTPS enforcement
    Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"
    
    # Content Security Policy for food business
    Content-Security-Policy = """
      default-src 'self';
      script-src 'self' 'unsafe-inline' 'unsafe-eval' https://www.googletagmanager.com https://connect.facebook.net https://www.google-analytics.com;
      style-src 'self' 'unsafe-inline' https://fonts.googleapis.com https://cdnjs.cloudflare.com;
      img-src 'self' data: https: blob: https://www.google-analytics.com https://www.facebook.com;
      font-src 'self' https://fonts.gstatic.com https://cdnjs.cloudflare.com;
      connect-src 'self' https://api.whatsapp.com https://graph.facebook.com https://www.google-analytics.com;
      frame-src 'self' https://www.google.com https://www.facebook.com;
      object-src 'none';
      base-uri 'self';
      form-action 'self' https://wa.me;
    """

# Static assets caching (images, fonts, etc.)
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Food images optimized caching
[[headers]]
  for = "/*.webp"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Vary = "Accept"

[[headers]]
  for = "/*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Vary = "Accept"

[[headers]]
  for = "/*.jpeg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Vary = "Accept"

[[headers]]
  for = "/*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Vary = "Accept"

# PWA manifest and service worker
[[headers]]
  for = "/site.webmanifest"
  [headers.values]
    Content-Type = "application/manifest+json"
    Cache-Control = "public, max-age=86400"

[[headers]]
  for = "/sw.js"
  [headers.values]
    Content-Type = "text/javascript"
    Cache-Control = "public, max-age=0, must-revalidate"

# Fonts caching
[[headers]]
  for = "/*.woff2"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Content-Type = "font/woff2"

##############################################################################
# PERFORMANCE & SEO OPTIMIZATIONS
##############################################################################

# Preload critical resources
[[headers]]
  for = "/index.html"
  [headers.values]
    Link = '''
      </assets/logo.png>; rel=preload; as=image,
      <https://fonts.googleapis.com/css2?family=Playfair+Display:wght@400;500;600;700&display=swap>; rel=preload; as=style,
      <https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&display=swap>; rel=preload; as=style,
      <https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700&display=swap>; rel=preload; as=style
    '''

##############################################################################
# NETLIFY FUNCTIONS & EDGE HANDLERS (Future features)
##############################################################################

# Analytics function (if needed for advanced tracking)
[[functions]]
  from = "/api/analytics"
  to = "/.netlify/functions/analytics"

# Contact form handler (WhatsApp integration)
[[functions]]
  from = "/api/contact"
  to = "/.netlify/functions/whatsapp-handler"

##############################################################################
# BUILD OPTIMIZATION
##############################################################################

[build.processing]
  # Skip processing already optimized files
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true
  canonical_urls = true

[build.processing.images]
  compress = true

##############################################################################
# ENVIRONMENT-SPECIFIC SETTINGS
##############################################################################

# Production environment
[context.production]
  command = "npm run build"
  [context.production.environment]
    NODE_ENV = "production"
    VITE_GA_TRACKING_ID = "G-XXXXXXXXXX"
    VITE_META_PIXEL_ID = "XXXXXXXXX"
    VITE_ENVIRONMENT = "production"

# Preview deployments (pull requests)
[context.deploy-preview]
  command = "npm run build"
  [context.deploy-preview.environment]
    NODE_ENV = "development"
    VITE_ENVIRONMENT = "preview"

# Branch deployments
[context.branch-deploy]
  command = "npm run build"
  [context.branch-deploy.environment]
    NODE_ENV = "development"
    VITE_ENVIRONMENT = "development"

##############################################################################
# NETLIFY PLUGINS FOR OPTIMIZATION
##############################################################################

[[plugins]]
  # Lighthouse CI for performance monitoring
  package = "netlify-plugin-lighthouse"
  
  [plugins.inputs]
    output_path = "./lighthouse"
    audit_urls = [
      "/",
      "/menu",
      "/about",
      "/contact"
    ]
    
[[plugins]]
  # Sitemap generation
  package = "netlify-plugin-sitemap"
  
  [plugins.inputs]
    buildDir = "dist"
    exclude = [
      "/admin/**",
      "/api/**"
    ]

[[plugins]]
  # Performance budget
  package = "netlify-plugin-bundle-analyzer"

##############################################################################
# FORM HANDLING (Contact forms to WhatsApp)
##############################################################################

# Contact form handling
[[forms]]
  from = "/contact"
  to = "https://wa.me/237699808260"

##############################################################################
# ERROR PAGES
##############################################################################

# Custom 404 page (handled by SPA routing)
# Netlify will serve index.html for 404s due to SPA redirect above

##############################################################################
# COMPRESSION & OPTIMIZATION
##############################################################################

# Enable Brotli compression
[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

# Asset optimization
[build.processing.images]
  compress = true

##############################################################################
# ANALYTICS & MONITORING
##############################################################################

# Netlify Analytics (included in Pro plans)
[analytics]
  provider = "netlify"

##############################################################################
# NOTES FOR BUEADELIGHTS TEAM
##############################################################################

# This configuration file optimizes the BueaDelights website for:
# 1. Fast loading in Buea, Cameroon (3G/4G networks)
# 2. SEO optimization for local search
# 3. Security best practices for food business
# 4. WhatsApp integration redirects
# 5. PWA functionality
# 6. Performance monitoring

# To update this configuration:
# 1. Modify this file
# 2. Commit to your Git repository
# 3. Netlify will automatically redeploy

# For support: https://docs.netlify.com/configure-builds/file-based-configuration/
